version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - ENVIRONMENT=development
    volumes:
      - ./app:/app/app  # Mount source code for hot reload
      - ./pyproject.toml:/app/pyproject.toml
    depends_on:
      - ollama
    networks:
      - orca-agents-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - orca-agents-network
    restart: unless-stopped
    # Uncomment the following lines if you have a GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
    driver: local

networks:
  orca-agents-network:
    driver: bridge 